import {
  Gauge,
  Search,
  Wand2,
  MessagesSquare,
  GraduationCap,
  HeartHandshake,
  Compass,
  TrendingUp,
  Sparkles,
  Flame,
  Footprints,
  Map,
  Trophy,
  Lock,
  Check,
  X,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Undo2,
  ChevronRight,
  Home,
  LayoutDashboard,
  User,
  Settings,
  LogOut,
  Menu,
  Plus,
  Pencil,
  Trash2,
  Upload,
  Download,
  FileSpreadsheet,
  BookOpen,
  Clock,
  Star,
  Award,
  Target,
  BarChart3,
  ShieldCheck,
  Info,
  ExternalLink,
  ListChecks,
  Cloud,
  Building2,
  Layers,
  Video,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Flag,
  Share2,
  ThumbsUp,
  Camera,
  Loader2,
  Captions,
  Filter,
  ArrowUpDown,
  Calendar,
  CalendarCheck,
  type LucideIcon,
} from "lucide-react";

// Maps the plain-string icon names stored in the database (kebab-case) to
// their lucide-react components, so admins can store icon choices as data.
export const ICONS: Record<string, LucideIcon> = {
  gauge: Gauge,
  search: Search,
  "wand-2": Wand2,
  "messages-square": MessagesSquare,
  "graduation-cap": GraduationCap,
  "heart-handshake": HeartHandshake,
  compass: Compass,
  "trending-up": TrendingUp,
  sparkles: Sparkles,
  flame: Flame,
  footprints: Footprints,
  map: Map,
  trophy: Trophy,
  lock: Lock,
  check: Check,
  x: X,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  undo: Undo2,
  home: Home,
  dashboard: LayoutDashboard,
  user: User,
  settings: Settings,
  logout: LogOut,
  menu: Menu,
  plus: Plus,
  edit: Pencil,
  delete: Trash2,
  upload: Upload,
  download: Download,
  spreadsheet: FileSpreadsheet,
  book: BookOpen,
  clock: Clock,
  star: Star,
  award: Award,
  target: Target,
  chart: BarChart3,
  shield: ShieldCheck,
  info: Info,
  external: ExternalLink,
  chevron: ChevronRight,
  "list-checks": ListChecks,
  cloud: Cloud,
  building: Building2,
  layers: Layers,
  video: Video,
  play: Play,
  pause: Pause,
  "volume-on": Volume2,
  "volume-off": VolumeX,
  flag: Flag,
  share: Share2,
  "thumbs-up": ThumbsUp,
  camera: Camera,
  spinner: Loader2,
  captions: Captions,
  filter: Filter,
  sort: ArrowUpDown,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
};

export function Icon({
  name,
  className,
  "aria-hidden": ariaHidden = true,
}: {
  name: string;
  className?: string;
  "aria-hidden"?: boolean;
}) {
  const Cmp = ICONS[name] ?? Info;
  return <Cmp className={className} aria-hidden={ariaHidden} />;
}
